=== matipohl/TDigital/Java Web/src/xml/restaurant.dtd
<!ELEMENT lunchMenu (item+)>
<!ELEMENT item (name,description,price)>
<!ATTLIST item category NMTOKEN #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== matipohl/TDigital/Java Web/src/xml/restaurant.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lunchMenu SYSTEM "restaurant.dtd">
<lunchMenu>
    <item category="entradas">
        <name>Ensalada con Pollo</name>
        <description>Una ensalada con pollo.</description>
        <price>$10.99</price>
    </item>
    <item category="entradas">
        <name>S치nduche de Pollo</name>
        <description>Un s치nduche de pollo. </description>
        <price>$12.99</price>
    </item>
    <item category="entradas">
        <name>S치nduche de Pastrami</name>
        <description>Un s치nduche hecho con pastrami.</description>
        <price>$13.99</price>
    </item>
    <item category="bebidas">
        <name>Coca-Cola</name>
        <description>Una gaseosa.</description>
        <price>$0.99</price>
    </item>
    <item category="bebidas">
        <name>Jugo de Naranja</name>
        <description>Un jugo hecho con naranjas.</description>
        <price>$0.99</price>
    </item>    
</lunchMenu>
